// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebkcggonudpymnslfoxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVia2NnZ29udWRweW1uc2xmb3h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4OTg0NjAsImV4cCI6MjA1MzQ3NDQ2MH0.n311smlthN77tU_hdtlbpp55Orza7Gm2uLISY4LSkZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);